_BASE_: "../Base-YOLOv7.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  META_ARCHITECTURE: "YOLOV5"
  BACKBONE:
    NAME: "build_cspdarknetx_backbone"

  DARKNET:
    WEIGHTS: ""
    DEPTH_WISE: False
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
  YOLO:
    ANCHORS:
      # [
      #   [[10, 13], [16, 30], [33, 23]],
      #   [[30, 61], [62, 45], [59, 119]],
      #   [[116, 90], [156, 198], [373, 326]],
      # ]
      [
        [[46.0, 56.0], [31.0, 37.0], [17.0, 19.0]],
        [[85.0, 106.0], [63.0, 79.0], [115.0, 143.0]],
        [[231.0, 298.0], [356.0, 458.0], [157.0, 199.0]],
      ]
    CLASSES: 2
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.6
    WIDTH_MUL: 0.50
    DEPTH_MUL: 0.33
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 0.05
      LAMBDA_CONF: 1.0
      LAMBDA_CLS: 0.5
      ANCHOR_RATIO_THRESH: 4.0

DATASETS:
  TRAIN: ("mask_train",)
  TEST: ("mask_val",)

INPUT:
  MIN_SIZE_TRAIN: (416, 512, 608, 768)
  MAX_SIZE_TRAIN: 1056
  MIN_SIZE_TEST: 672
  MAX_SIZE_TEST: 768
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: False
  # MOSAIC:
  #   ENABLED: True
  #   NUM_IMAGES: 4
  #   DEBUG_VIS: True
  #   # MOSAIC_WIDTH: 960
  #   # MOSAIC_HEIGHT: 540
  MOSAIC_AND_MIXUP:
    ENABLED: True
    DEBUG_VIS: False
    ENABLE_MIXUP: False

SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.046
  STEPS: (60000, 80000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 1500
  MAX_ITER: 150000
  LR_SCHEDULER_NAME: "WarmupCosineLR"

TEST:
  EVAL_PERIOD: 5000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/wearmask_yolov5_s"
VIS_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 1
