cond_check_size_image: True
original_width_min_cutoff: 150
original_width_max_cutoff: 10_000
original_height_min_cutoff: 150
original_height_max_cutoff: 10_000
aspect_ratio_max_cutoff: 3
cond_check_number_words: True
number_words_min_cutoff: 1
number_words_max_cutoff: 256
cond_check_word_repetition_ratio: True
word_repetition_length: 1
word_repetition_max_cutoff: 0.7
cond_check_special_character_ratio: True
special_character_ratio_max_cutoff: 0.4
cond_check_common_word_ratio: True
common_word_ratio_min_cutoff: 0.7
