_BASE_: "../Base-YoloV7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  YOLO:
    ANCHORS:
      [
        [[48, 113], [85, 39], [30, 73]],
        [[20, 48], [40, 19], [14, 34]],
        [[10, 24], [21, 9], [6, 15]],
      ]
    CLASSES: 5
    IN_FEATURES: ["res3", "res4", "res5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.1
    NMS_THRESHOLD: 0.2
    IGNORE_THRESHOLD: 0.5
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"

DATASETS:
  TRAIN: ("tl_train",)
  TEST: ("tl_val",)

INPUT:
  # open all augmentations
  JITTER_CROP:
    ENABLED: True
  RESIZE:
    ENABLED: True
    SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True
    NUM_IMAGES: 4
    MOSAIC_WIDTH: 960
    MOSAIC_HEIGHT: 540

SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.000064
  WARMUP_ITERS: 1000
  STEPS: (60000, 80000)
  MAX_ITER: 120000
  CLIP_GRADIENTS:
    ENABLED: True
  CHECKPOINT_PERIOD: 5000


OUTPUT_DIR: "output/tl_r50_fpn"

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2
