_BASE_: "../Base-YoloV7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  # WEIGHTS: "weights/r2_50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "build_res2net_fpn_backbone"
  RESNETS:
    DEPTH: 34
    # WIDTH_PER_GROUP: 26
    RES2_OUT_CHANNELS: 64
    # DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 512
  YOLO:
    ANCHORS:
      [
        [[48, 113], [85, 39], [30, 73]],
        [[20, 48], [40, 19], [14, 34]],
        [[10, 24], [21, 9], [6, 15]],
      ]
    CLASSES: 5
    IN_FEATURES: ["p3", "p4", "p5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.2
    NMS_THRESHOLD: 0.1
    IGNORE_THRESHOLD: 0.1
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"

DATASETS:
  TRAIN: ("tl_train",)
  TEST: ("tl_val",)

INPUT:
  # open all augmentations
  JITTER_CROP:
    ENABLED: True
  RESIZE:
    ENABLED: True
    SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True
    NUM_IMAGES: 4
    MOSAIC_WIDTH: 960
    MOSAIC_HEIGHT: 540

SOLVER:
  IMS_PER_BATCH: 48
  BASE_LR: 0.0009
  STEPS: (70000, 90000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2
