_BASE_: "../Base-YoloV7.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  META_ARCHITECTURE: "YOLOV7P"
  BACKBONE:
    NAME: "build_cspdarknetx_backbone"
    
  DARKNET:
    WEIGHTS: ""
    DEPTH_WISE: False
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
  YOLO:
    ANCHORS:
      [
        [[10, 24], [21, 9], [6, 15]],
        [[20, 48], [40, 19], [14, 34]],
        [[48, 113], [85, 39], [30, 73]],
      ]
      # [
      #   [[48, 113], [85, 39], [30, 73]],
      #   [[20, 48], [40, 19], [14, 34]],
      #   [[10, 24], [21, 9], [6, 15]],
      # ]
    CLASSES: 5
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.5
    IGNORE_THRESHOLD: 0.6
    WIDTH_MUL: 0.50
    DEPTH_MUL: 0.33
    LOSS_TYPE: "v7"

DATASETS:
  TRAIN: ("tl_train",)
  TEST: ("tl_val",)


INPUT:
  # open all augmentations
  JITTER_CROP:
    ENABLED: True
  RESIZE:
    ENABLED: True
    SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True
    NUM_IMAGES: 4
    MOSAIC_WIDTH: 960
    MOSAIC_HEIGHT: 540

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.006
  WARMUP_ITERS: 1000
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CLIP_GRADIENTS:
    ENABLED: True
  CHECKPOINT_PERIOD: 1000

TEST:
  # EVAL_PERIOD: 5000
  EVAL_PERIOD: 0
OUTPUT_DIR: "output/tl_darknetx_pafpn"
VIS_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 8
