_BASE_: "../Base-YOLOv7.yaml"
MODEL:
  PIXEL_MEAN: [0.485, 0.456, 0.406] # same value as PP-YOLOv2, RGB order
  PIXEL_STD: [0.229, 0.224, 0.225]

  WEIGHTS: ""
  MASK_ON: False
  META_ARCHITECTURE: "YOLOX"
  BACKBONE:
    NAME: "build_cspdarknetx_backbone"

  DARKNET:
    WEIGHTS: ""
    DEPTH_WISE: False
    OUT_FEATURES: ["dark3", "dark4", "dark5"]

  YOLO:
    CLASSES: 5
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    # CONF_THRESHOLD: 0.01
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.7
    WIDTH_MUL: 0.50
    DEPTH_MUL: 0.33
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 1.5

DATASETS:
  TRAIN: ("tl_train",)
  TEST: ("tl_val",)

INPUT:
  # FORMAT: "RGB" # using BGR default
  MIN_SIZE_TRAIN: (416, 512, 608, 768, 800)
  MAX_SIZE_TRAIN: 1920 # force max size train to 800?
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1920
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  # MOSAIC:
  #   ENABLED: True
  #   NUM_IMAGES: 4
  #   DEBUG_VIS: True
  #   # MOSAIC_WIDTH: 960
  #   # MOSAIC_HEIGHT: 540
  MOSAIC_AND_MIXUP:
    ENABLED: True
    DEBUG_VIS: False
    ENABLE_MIXUP: True
    DISABLE_AT_ITER: 120000

SOLVER:
  # enable fp16 training
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 112
  # IMS_PER_BATCH: 12
  BASE_LR: 0.025
  STEPS: (60000, 80000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 1500
  MAX_ITER: 150000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 5000

TEST:
  EVAL_PERIOD: 5000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/tl_yolox_s"
VIS_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 3
