MODEL:
  META_ARCHITECTURE: "YOLOV7" # default is YOLO, can be YOLOV7, YOLOX, YOLOMASK as well
  PIXEL_MEAN: [0.406, 0.485, 0.456] # same value as PP-YOLOv2, BGR order
  PIXEL_STD: [0.225, 0.229, 0.224]
  PADDED_VALUE: 114.0

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupCosineLR"

INPUT:
  FORMAT: "BGR" # let's force BGR here, since our mean and std are BGR order. if PIL read it, it should convert to BGR
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TEST: 608

VERSION: 2
