_BASE_: "Base-SparseInst.yaml"
MODEL:
  RESNETS:
    DEFORM_ON_PER_STAGE: [False, False, True, True] # dcn on res4, res5
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/sparse_inst_r50_dcn_giam_aug"