_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "../../pretrained_models/resnet50d_ra2-464e36ba.pth"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd_backbone"
OUTPUT_DIR: "output/sparse_inst_r50vd_giam"
