_BASE_: "../Base-YoloV7.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  LOAD_PROPOSALS: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"] # we might also want try res2, res3, res4, res5
  YOLO:
    ANCHORS:
      [
        [[116, 90], [156, 198], [373, 326]],
        [[30, 61], [62, 45], [42, 119]],
        [[10, 13], [16, 30], [33, 23]],
      ]
    CLASSES: 80
    IN_FEATURES: ["res3", "res4", "res5"]
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.5
    IGNORE_THRESHOLD: 0.7
    VARIANT: "yolov7"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2