_BASE_: "../Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  WEIGHTS: ""
  MASK_ON: False
  BACKBONE:
    NAME: "build_res2net_backbone"
  RESNETS:
    R2TYPE: "res2net50_v1b"
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  YOLO:
    ANCHORS:
      [
        [[116, 90], [156, 198], [373, 326]],
        [[30, 61], [62, 45], [42, 119]],
        [[10, 13], [16, 30], [33, 23]],
      ]
    CLASSES: 80
    IN_FEATURES: ["res3", "res4", "res5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.7
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
    WIDTH_MUL: 2.0 # for FPN neck
    LOSS:
      LAMBDA_IOU: 1.1
    NECK:
      TYPE: "fpn"
      WITH_SPP: true

DATASETS:
  TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2014_val_mini",)
  TEST: ("coco_2017_val",)


INPUT:
  MIN_SIZE_TRAIN: (416, 512, 608, 768)
  MAX_SIZE_TRAIN: 1056
  MIN_SIZE_TEST: 672
  MAX_SIZE_TEST: 768
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: False
  # MOSAIC:
  #   ENABLED: True
  #   NUM_IMAGES: 4
  #   DEBUG_VIS: True
  #   # MOSAIC_WIDTH: 960
  #   # MOSAIC_HEIGHT: 540
  MOSAIC_AND_MIXUP:
    ENABLED: True
    DEBUG_VIS: False
    ENABLE_MIXUP: False


SOLVER:
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 32 # 1/5 bs than YOLOX
  # it can be 0.016 maybe
  BASE_LR: 0.0018
  STEPS: (60000, 80000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 1500
  MAX_ITER: 190000
  LR_SCHEDULER_NAME: "WarmupCosineLR"


TEST:
  EVAL_PERIOD: 10000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/coco_r2_50_l"

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 1
