name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CUDA_VERSION: "11.7"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install DeepSeek-VL
        env:
          USE_FP16: "OFF"
          TORCH_CUDA_ARCH_LIST: "Auto"
        run: |
          python -m pip install torch numpy pybind11
          python -m pip install -vvv --no-build-isolation --editable '.[lint]'

      - name: black
        run: |
          make black-format

      - name: addlicense
        run: |
          make addlicense