_BASE_: "../Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  WEIGHTS: ""
  MASK_ON: False
  BACKBONE:
    NAME: "build_cspdarknet_backbone"
  DARKNET:
    WEIGHTS: "weights/yolov3.pt" # using pytorch weights from ultralytics's yolov3
    DEPTH: 53
    WITH_CSP: True
    STEM_OUT_CHANNELS: 32
    WEIGHTS: ""
    OUT_FEATURES: ["layer3", "layer4", "layer5"]
  YOLO:
    ANCHORS:
      [
        [[322, 428], [194, 260], [123, 168]],
        [[84, 115], [60, 79], [41, 53]],
        [[27, 37], [18, 23], [10, 13]],
      ]
    CLASSES: 2
    IN_FEATURES: ["layer3", "layer4", "layer5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.2
    IGNORE_THRESHOLD: 0.5
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
DATASETS:
  TRAIN: ("facemask_train",)
  TEST: ("facemask_val",)

INPUT:
  # open all augmentations
  JITTER_CROP:
    ENABLED: True
  RESIZE:
    ENABLED: True
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True
    NUM_IMAGES: 4
    # MOSAIC_WIDTH: 960
    # MOSAIC_HEIGHT: 540

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 120000

TEST:
  EVAL_PERIOD: 10000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/facemask_cspdarknet"

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2