_BASE_: "../Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    RES2_OUT_CHANNELS: 256 # align with darknet output channels
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  YOLO:
    ANCHORS:
      [
        [[322, 428], [194, 260], [123, 168]],
        [[84, 115], [60, 79], [41, 53]],
        [[27, 37], [18, 23], [10, 13]],
      ]
    CLASSES: 2
    IN_FEATURES: ["res3", "res4", "res5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.2
    IGNORE_THRESHOLD: 0.5
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
DATASETS:
  TRAIN: ("facemask_train",)
  TEST: ("facemask_val",)

INPUT:
  # open all augmentations
  JITTER_CROP:
    ENABLED: True
  RESIZE:
    ENABLED: True
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True
    NUM_IMAGES: 4
    # MOSAIC_WIDTH: 960
    # MOSAIC_HEIGHT: 540


SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00008
  STEPS: (60000, 80000)
  MAX_ITER: 270000


TEST:
  EVAL_PERIOD: 10000
  # EVAL_PERIOD: 0

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2
