MODEL:
  META_ARCHITECTURE: "DetrD2go"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    NUM_CLASSES: 80
    CLS_WEIGHT: 2.0
    DIM_FEEDFORWARD: 1024
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 300
    CENTERED_POSITION_ENCODIND: True
    USE_FOCAL_LOSS: True
    NUM_FEATURE_LEVELS: 1
    ATTENTION_TYPE: 'DETR'

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

SOLVER:
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (887040,)
  MAX_ITER: 1108800
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  LR_MULTIPLIER_OVERWRITE: [{'backbone': 0.1}, {'reference_points': 0.1, 'sampling_offsets': 0.1}]
  # BACKBONE_MULTIPLIER: 0.1
  
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
# D2GO_DATA:
#   MAPPER:
#     NAME: "DETRDatasetMapper"

TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2

