extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MinMaxObserver
        a_observer: EMAMinMaxObserver
        w_fakequantize: LearnableFakeQuantize
        a_fakequantize: LearnableFakeQuantize
        w_qscheme:
            bit: 8
            # symmetry: False
            symmetry: true
            per_channel: True
            pot_scale: False
        a_qscheme:
            bit: 8
            # symmetry: False
            symmetry: true
            per_channel: False
            pot_scale: False
quantize:
    quantize_type: naive_ptq # support naive_ptq or advanced_ptq
    cali_batchsize: 16
    # backend: 'Tensorrt'
    backend: 'ONNX_QNN'
    # backend: 'PPLW8A16'
    deploy:
        model_name: 'r18.onnx'
        output_path: './'
        deploy_to_qlinear: true
model:                    # architecture details
    type: resnet18        # model name
    kwargs:
        num_classes: 1000
    path: /path-of-pretrained
data:
    path: /path-of-imagenet
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005